app:
  corsAllowedOrigins: http://localhost:3000
  storage:
    path: E:\Files\Media\
    startupMode: append
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:file:./db
    driverClassName: org.h2.Driver
    username: sa
    password: MyLifeTimeline
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
